### ISSUE TITLE
Potentiomètres

### ISSUE THREAD

**Issue by JackDesBwa** [haum/ponghaum#2]
Ajouter la gestion des potentiomètres (A0, A1) dans le cœur du système.
Pas d'accès dans l'API : ils servent à ajuster la luminosité et la fréquence d'animation seulement.

**Comment by jblb** [comment]
comme ce soir y avais bricodage autour du pong cen ai ou cette histoire de potentiometres

**Comment by Matael** [comment]
Du coup, en posant la question à la cantonnade, on obtient une réponse ! Il s'avère que les potentiomètres sont inclus dans haum/polychrhaum mais pas dans le pong. Avis aux amateurs !

**Comment by jblb** [comment]
reste donc juste a savoir comment utiliser haum/polychrhaum ;)

**Comment by JackDesBwa** [comment]
Semble résolu par :
https://github.com/haum/polychrhaum/commit/b02422aa6dcf1d1ae66d12da2c020a89d8078705
