### ISSUE TITLE
Imprimer les manettes pour le second pong

### ISSUE THREAD

**Issue by JackDesBwa** [haum/ponghaum#3]

**Comment by MicroJoe** [comment]
Les manettes ayant été imprimées (mais utilisées dans le premier pong), est-ce qu'on envisage une seconde impression ou alors on garde les anciennes manettes pour la version "hackable" ?

**Comment by sebvallee** [comment]
Je crois savoir que plusieurs jeux de manettes ont été imprimées... A vérifier auprès de @Matael...

**Comment by Matael** [comment]
En effet, j'ai oublié de les descendre, mais je le ferais sous peu. Il y a deux autres manettes prêtes chez mkshp (je n'utilise pas le nom complet pour éviter l'indexation du commentaire, sorry).

**Comment by Matael** [comment]
Les manettes sont (enfin) au HAUM.
